packages:
  - packages/*

catalogMode: strict

catalogs:
  default:
    '@biomejs/biome': 2.3.5
    '@types/node': ^24.10.2
    '@vitest/coverage-v8': ^4.0.15
    typescript: ^5.9.3i
    vitest: ^4.0.15

onlyBuiltDependencies:
  - esbuild
  - '@sentry/cli'
  - '@biomejs/biome'
  - bufferutil
  - zlib-sync
