packages:
  - packages/*

enableGlobalVirtualStore: true

configDependencies:
  '@pnpm/plugin-esm-node-path': 0.1.2+sha512-KzcFbJpNJHRZ60GpXmc6CoBX/zjy+fKEf/OOYdRbAlxV/Kf/f6pDNUDIVTQU8a5DHt6ODXq5mndwJPlryqMj1A==

catalogMode: strict

catalogs:
  default:
    '@biomejs/biome': 2.4.9
    '@types/node': ^24.12.0
    '@vitest/coverage-v8': ^4.1.1
    typescript: ^5.9.3i
    vitest: ^4.1.1

onlyBuiltDependencies:
  - esbuild
  - '@sentry/cli'
  - '@biomejs/biome'
  - bufferutil
  - zlib-sync

packageExtensions:
  discord-player:
    dependencies:
      discord-api-types: '*'
      discord.js: '*'
      undici: '*'
      '@discord-player/opus': '*'
  discord-voip:
    dependencies:
      discord-api-types: '*'
      ws: '*'
      '@discord-player/equalizer': '*'
      '@snazzah/davey': '*'
  discord-player-spotify:
    peerDependencies:
      discord-player: '*'
