packages:
  - packages/*

catalogMode: strict

catalogs:
  default:
    '@biomejs/biome': 2.3.0
    '@changesets/cli': ^2.29.7
    '@types/node': ^24.9.1
    '@vitest/coverage-v8': ^3.2.4
    typescript: ^5.9.3
    vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - '@sentry/cli'
  - '@biomejs/biome'
  - bufferutil
  - zlib-sync
