packages:
  - 'packages/*'

catalogs:
  default:
    '@biomejs/biome': 2.3.0
    '@types/jsdom': ^27.0.0
    '@types/node': ^24.9.1
    '@vitest/coverage-v8': 3.2.4
    bgutils-js: ^3.2.0
    googlevideo: ^4.0.4
    jsdom: ^27.0.1
    typescript: ^5.9.3
    vitest: ^3.2.4
    youtubei.js: ^16.0.1
