packages:
  - packages/*
allowBuilds:
  '@biomejs/biome': true
  '@sentry/cli': true
  bufferutil: true
  esbuild: true
  zlib-sync: true

catalogMode: strict

dedupePeers: true

minimumReleaseAge: 1440

catalogs:
  default:
    '@biomejs/biome': 2.5.11
    '@types/node': ^24.13.3
    '@vitest/coverage-v8': ^4.1.11
    typescript: ^7.0.2
    vitest: ^4.1.11

enableGlobalVirtualStore: true

overrides:
  libsodium-wrappers: '-'

packageExtensions:
  discord-player:
    dependencies:
      '@discord-player/opus': '*'
      discord-api-types: '*'
      discord.js: '*'
      undici: '*'
  discord-player-spotify:
    peerDependencies:
      discord-player: '*'
  discord-voip:
    dependencies:
      '@discord-player/equalizer': '*'
      '@snazzah/davey': '*'
      discord-api-types: '*'
      ws: '*'
