packages:
  - packages/*
allowBuilds:
  '@biomejs/biome': true
  '@sentry/cli': true
  bufferutil: true
  esbuild: true
  zlib-sync: true

catalogMode: strict

catalogs:
  default:
    '@biomejs/biome': 2.4.13
    '@types/node': ^24.12.2
    '@vitest/coverage-v8': ^4.1.4
    typescript: ^5.9.3i
    vitest: ^4.1.4

configDependencies:
  '@pnpm/plugin-esm-node-path': 0.1.2+sha512-KzcFbJpNJHRZ60GpXmc6CoBX/zjy+fKEf/OOYdRbAlxV/Kf/f6pDNUDIVTQU8a5DHt6ODXq5mndwJPlryqMj1A==

enableGlobalVirtualStore: true

packageExtensions:
  discord-player:
    dependencies:
      '@discord-player/opus': '*'
      discord-api-types: '*'
      discord.js: '*'
      undici: '*'
  discord-player-spotify:
    peerDependencies:
      discord-player: '*'
  discord-voip:
    dependencies:
      '@discord-player/equalizer': '*'
      '@snazzah/davey': '*'
      discord-api-types: '*'
      ws: '*'
